-- ============================================================
-- PETROVA – RBAC Setup (4-Role Hierarchy)
-- Ref: Agent.MD Section 6 – Gold Immutability Commandment #6
-- ============================================================

-- Role hierarchy:
--   PETROVA_ADMIN → PETROVA_ENGINEER → PETROVA_ANALYST → PETROVA_READER

-- 1. Create roles
CREATE ROLE IF NOT EXISTS PETROVA_READER;
CREATE ROLE IF NOT EXISTS PETROVA_ANALYST;
CREATE ROLE IF NOT EXISTS PETROVA_ENGINEER;
CREATE ROLE IF NOT EXISTS PETROVA_ADMIN;

-- 2. Role hierarchy (inheritance)
GRANT ROLE PETROVA_READER   TO ROLE PETROVA_ANALYST;
GRANT ROLE PETROVA_ANALYST  TO ROLE PETROVA_ENGINEER;
GRANT ROLE PETROVA_ENGINEER TO ROLE PETROVA_ADMIN;
GRANT ROLE PETROVA_ADMIN    TO ROLE SYSADMIN;

-- 3. Warehouse grants
GRANT USAGE ON WAREHOUSE PETROVA_PROD_WH TO ROLE PETROVA_READER;
GRANT USAGE ON WAREHOUSE PETROVA_PROD_WH TO ROLE PETROVA_ANALYST;
GRANT USAGE ON WAREHOUSE PETROVA_ETL_WH  TO ROLE PETROVA_ENGINEER;
GRANT ALL   ON WAREHOUSE PETROVA_DEV_WH  TO ROLE PETROVA_ENGINEER;

-- 4. Database grants
GRANT USAGE ON DATABASE PETROVA_PROD TO ROLE PETROVA_READER;
GRANT USAGE ON DATABASE PETROVA_DEV  TO ROLE PETROVA_ENGINEER;

-- 5. Schema-level grants (Medallion RBAC)

-- BRONZE: Engineers can read/write; Analysts can read
GRANT USAGE ON SCHEMA PETROVA_PROD.BRONZE TO ROLE PETROVA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA PETROVA_PROD.BRONZE TO ROLE PETROVA_ANALYST;
GRANT ALL ON SCHEMA PETROVA_PROD.BRONZE TO ROLE PETROVA_ENGINEER;

-- SILVER: Engineers can read/write; Analysts can read
GRANT USAGE ON SCHEMA PETROVA_PROD.SILVER TO ROLE PETROVA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA PETROVA_PROD.SILVER TO ROLE PETROVA_ANALYST;
GRANT ALL ON SCHEMA PETROVA_PROD.SILVER TO ROLE PETROVA_ENGINEER;

-- GOLD: Read-only for everyone except procedures (Immutability!)
GRANT USAGE ON SCHEMA PETROVA_PROD.GOLD TO ROLE PETROVA_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA PETROVA_PROD.GOLD TO ROLE PETROVA_READER;
-- Engineers can EXECUTE procedures (the only way to write to Gold)
GRANT USAGE ON ALL PROCEDURES IN SCHEMA PETROVA_PROD.GOLD TO ROLE PETROVA_ENGINEER;

-- AUDIT: Engineers can write; Analysts can read
GRANT USAGE ON SCHEMA PETROVA_PROD.AUDIT TO ROLE PETROVA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA PETROVA_PROD.AUDIT TO ROLE PETROVA_ANALYST;
GRANT ALL ON SCHEMA PETROVA_PROD.AUDIT TO ROLE PETROVA_ENGINEER;

-- 6. Future grants (auto-apply to new objects)
GRANT SELECT ON FUTURE TABLES IN SCHEMA PETROVA_PROD.GOLD TO ROLE PETROVA_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PETROVA_PROD.SILVER TO ROLE PETROVA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PETROVA_PROD.BRONZE TO ROLE PETROVA_ANALYST;
